wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1657716779
    t:
      1:
      - 55
      2:
      - 55
      4: 3.9.13
      5: 0.12.17
      8:
      - 5
input_artifact:
  desc: null
  value: domenico-vesia/nyc_airbnb/sample.csv:latest
max_price:
  desc: null
  value: 350.0
min_price:
  desc: null
  value: 10.0
output_artifact:
  desc: null
  value: clean_sample.csv
output_description:
  desc: null
  value: Data without outliers and null values
output_type:
  desc: null
  value: clean sample
