wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1658386510
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      4: 3.8.13
      5: 0.12.17
      8:
      - 5
criterion:
  desc: null
  value: mae
max_depth:
  desc: null
  value: 15
max_features:
  desc: null
  value: 0.1
max_tfidf_features:
  desc: null
  value: 10
min_samples_leaf:
  desc: null
  value: 3
min_samples_split:
  desc: null
  value: 4
n_estimators:
  desc: null
  value: 100
n_jobs:
  desc: null
  value: -1
oob_score:
  desc: null
  value: true
output_artifact:
  desc: null
  value: random_forest_export
random_seed:
  desc: null
  value: 42
rf_config:
  desc: null
  value: /home/coding/Scrivania/MLOps-Udacity/Projects/MLOps-Udacity/airbnb_nyc/multirun/2022-07-21/08-55-04/0/rf_config.json
stratify_by:
  desc: null
  value: neighbourhood_group
trainval_artifact:
  desc: null
  value: domenico-vesia/nyc_airbnb/trainval_data.csv:latest
val_size:
  desc: null
  value: 0.2
